var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled, { keyframes } from 'styled-components';
var atomSpinnerAnimation1 = keyframes(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    100% {\n        transform: rotateZ(120deg) rotateX(66deg) rotateZ(360deg);\n    }\n"], ["\n    100% {\n        transform: rotateZ(120deg) rotateX(66deg) rotateZ(360deg);\n    }\n"])));
var atomSpinnerAnimation2 = keyframes(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    100% {\n        transform: rotateZ(240deg) rotateX(66deg) rotateZ(360deg);\n    }\n"], ["\n    100% {\n        transform: rotateZ(240deg) rotateX(66deg) rotateZ(360deg);\n    }\n"])));
var atomSpinnerAnimation3 = keyframes(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    100% {\n        transform: rotateZ(360deg) rotateX(66deg) rotateZ(360deg);\n    }\n"], ["\n    100% {\n        transform: rotateZ(360deg) rotateX(66deg) rotateZ(360deg);\n    }\n"])));
var AtomSpinner = styled.div(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n    height: ", "px;\n    width: ", "px;\n    overflow: hidden;\n    .atom-spinner * {\n        box-sizing: border-box;\n    }\n"], ["\n    height: ", "px;\n    width: ", "px;\n    overflow: hidden;\n    .atom-spinner * {\n        box-sizing: border-box;\n    }\n"])), function (props) { var _a; return (_a = props.style) === null || _a === void 0 ? void 0 : _a.height; }, function (props) { var _a; return (_a = props.style) === null || _a === void 0 ? void 0 : _a.width; });
var AtomSpinnerInner = styled.div(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n    position: relative;\n    display: block;\n    height: 100%;\n    width: 100%;\n"], ["\n    position: relative;\n    display: block;\n    height: 100%;\n    width: 100%;\n"])));
var SpinnerCircle = styled.div(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n    display: block;\n    position: absolute;\n    color: ", ";\n    font-size: calc(60px * 0.24);\n    top: 50%;\n    left: 50%;\n    transform: translate(-50%, -50%);\n"], ["\n    display: block;\n    position: absolute;\n    color: ", ";\n    font-size: calc(60px * 0.24);\n    top: 50%;\n    left: 50%;\n    transform: translate(-50%, -50%);\n"])), function (props) { var _a; return (_a = props.style) === null || _a === void 0 ? void 0 : _a.color; });
var SpinnerLine = styled.div(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n    position: absolute;\n    width: 100%;\n    height: 100%;\n    border-radius: 50%;\n    animation-duration: ", "s;\n    border-left-width: calc(60px / 25);\n    border-top-width: calc(60px / 25);\n    border-left-color: ", ";\n    border-left-style: solid;\n    border-top-style: solid;\n    border-top-color: transparent;\n   \n    &:nth-child(1) {\n        animation: ", " infinite;\n        animation-duration: ", "s;\n        animation-timing-function: linear;\n        transform: rotateZ(120deg) rotateX(66deg) rotateZ(0deg);  \n    }\n    &:nth-child(2) {\n        animation: ", " infinite;\n        animation-duration: ", "s;\n        animation-timing-function: linear;\n        transform: rotateZ(240deg) rotateX(66deg) rotateZ(0deg);  \n    }\n    &:nth-child(3) {\n        animation: ", " infinite;\n        animation-duration: ", "s;\n        animation-timing-function: linear;\n        transform: rotateZ(360deg) rotateX(66deg) rotateZ(0deg);  \n    }\n \n"], ["\n    position: absolute;\n    width: 100%;\n    height: 100%;\n    border-radius: 50%;\n    animation-duration: ", "s;\n    border-left-width: calc(60px / 25);\n    border-top-width: calc(60px / 25);\n    border-left-color: ", ";\n    border-left-style: solid;\n    border-top-style: solid;\n    border-top-color: transparent;\n   \n    &:nth-child(1) {\n        animation: ", " infinite;\n        animation-duration: ", "s;\n        animation-timing-function: linear;\n        transform: rotateZ(120deg) rotateX(66deg) rotateZ(0deg);  \n    }\n    &:nth-child(2) {\n        animation: ", " infinite;\n        animation-duration: ", "s;\n        animation-timing-function: linear;\n        transform: rotateZ(240deg) rotateX(66deg) rotateZ(0deg);  \n    }\n    &:nth-child(3) {\n        animation: ", " infinite;\n        animation-duration: ", "s;\n        animation-timing-function: linear;\n        transform: rotateZ(360deg) rotateX(66deg) rotateZ(0deg);  \n    }\n \n"])), function (props) { return props.itemProp; }, function (props) { var _a; return (_a = props.style) === null || _a === void 0 ? void 0 : _a.color; }, atomSpinnerAnimation1, function (props) { return props.itemProp; }, atomSpinnerAnimation2, function (props) { return props.itemProp; }, atomSpinnerAnimation3, function (props) { return props.itemProp; });
export { AtomSpinner, AtomSpinnerInner, SpinnerCircle, SpinnerLine };
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7;
