import React from 'react';
import './App.scss';
import { Atom, Orbit, Trinity, Electron, Square } from './spinners/index';
function App() {
    return (React.createElement(React.Fragment, null,
        React.createElement("div", { className: "main-container" },
            React.createElement("div", { className: "title-holder" },
                React.createElement("h1", { className: "header" }, "React Epic Spinners"),
                React.createElement("h5", { className: "sub-header" },
                    "React Implementation of",
                    React.createElement("a", { className: "link", href: "http://epic-react-spinners.es/", target: "_blank", rel: "noreferrer" }, " Epic Spinners")),
                React.createElement("div", { className: "get-started" },
                    React.createElement("div", { className: "get-started__docs" },
                        React.createElement("h4", null, "Get started"),
                        React.createElement("a", { href: "https://github.com/p4pupro/epic-react-spinners", className: "docs" }, "Docs")),
                    React.createElement("div", { className: "get-started-code" },
                        React.createElement("p", null, "npm install epic-react-spinners"),
                        React.createElement("p", null, "yarn add epic-react-spinners")))),
            React.createElement("div", { className: "spinner-holder" },
                React.createElement("div", { className: "spinner-element" },
                    React.createElement(Atom, { color: "#61dafb", size: "70", animationDuration: "2" })),
                React.createElement("div", { className: "name" }, "Atom Spinner")),
            React.createElement("div", { className: "spinner-holder" },
                React.createElement("div", { className: "spinner-element" },
                    React.createElement(Orbit, { color: "#61dafb", size: "70", animationDuration: "2" })),
                React.createElement("div", { className: "name" }, "Orbit Spinner")),
            React.createElement("div", { className: "spinner-holder" },
                React.createElement("div", { className: "spinner-element" },
                    React.createElement(Trinity, { color: "#61dafb", size: "70", animationDuration: "2" })),
                React.createElement("div", { className: "name" }, "Trinity Spinner")),
            React.createElement("div", { className: "spinner-holder" },
                React.createElement("div", { className: "spinner-element" },
                    React.createElement(Electron, { color: "#61dafb", size: "70", animationDuration: "2" })),
                React.createElement("div", { className: "name" }, "Electron Spinner")),
            React.createElement("div", { className: "spinner-holder" },
                React.createElement("div", { className: "spinner-element" },
                    React.createElement(Square, { color: "#61dafb", size: "70", animationDuration: "2" })),
                React.createElement("div", { className: "name" }, "Squares Spinner"))),
        React.createElement("footer", null,
            React.createElement("h4", null,
                "By",
                React.createElement("a", { href: "https://github.com/p4pupro", className: "link" }, " @p4pupro")),
            React.createElement("p", null,
                "This project is an implementation of the",
                React.createElement("a", { href: "https://github.com/p4pupro/epic-spinners", target: "_blank", rel: "noreferrer", className: "link" }, " Epic Spinners"),
                " project created by",
                React.createElement("a", { href: "https://github.com/p4pupro", target: "_blank", rel: "noreferrer", className: "link" }, " p4pupro")))));
}
export default App;
