var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled, { keyframes } from 'styled-components';
var electronSpinnerAnimation1 = keyframes(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    0%  {\n        transform: rotateX(35deg) rotateY(-45deg) rotateZ(0deg);\n    }\n    100% {\n        transform: rotateX(35deg) rotateY(-45deg) rotateZ(360deg);\n    }\n"], ["\n    0%  {\n        transform: rotateX(35deg) rotateY(-45deg) rotateZ(0deg);\n    }\n    100% {\n        transform: rotateX(35deg) rotateY(-45deg) rotateZ(360deg);\n    }\n"])));
var electronSpinnerAnimation2 = keyframes(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    0% {\n        transform: rotateX(50deg) rotateY(10deg) rotateZ(0deg);\n    }\n    100% {\n        transform: rotateX(50deg) rotateY(10deg) rotateZ(360deg);\n    }\n"], ["\n    0% {\n        transform: rotateX(50deg) rotateY(10deg) rotateZ(0deg);\n    }\n    100% {\n        transform: rotateX(50deg) rotateY(10deg) rotateZ(360deg);\n    }\n"])));
var electronSpinnerAnimation3 = keyframes(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    0% {\n        transform: rotateX(35deg) rotateY(55deg) rotateZ(0deg);\n    }\n    100% {\n        transform: rotateX(35deg) rotateY(55deg) rotateZ(360deg);\n    }\n"], ["\n    0% {\n        transform: rotateX(35deg) rotateY(55deg) rotateZ(0deg);\n    }\n    100% {\n        transform: rotateX(35deg) rotateY(55deg) rotateZ(360deg);\n    }\n"])));
var ElectronSpinner = styled.div(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n    border-radius: 50%;\n    perspective: 800px;\n    height: ", "px;\n    width: ", "px;\n"], ["\n    border-radius: 50%;\n    perspective: 800px;\n    height: ", "px;\n    width: ", "px;\n"])), function (props) { var _a; return (_a = props.style) === null || _a === void 0 ? void 0 : _a.height; }, function (props) { var _a; return (_a = props.style) === null || _a === void 0 ? void 0 : _a.width; });
var ElectronLine = styled.div(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n    position: absolute;\n    box-sizing: border-box;\n    width: 100%;\n    height: 100%;\n    border-radius: 50%;\n\n    &:nth-child(1) {\n        left: 0;\n        top: 0;\n        animation: ", " infinite;\n        border-bottom: 3px solid ", ";\n        animation-duration: ", "s;\n        animation-timing-function: linear;\n        \n    }\n    &:nth-child(2) {\n        right: 0;\n        top: 0;\n        animation: ", " infinite;\n        border-right: 3px solid ", ";\n        animation-duration: ", "s;\n        animation-timing-function: linear; \n    }\n    &:nth-child(3) {\n        right: 0;\n        bottom: 0;\n        animation: ", " infinite;\n        border-right: 3px solid ", ";\n        animation-duration: ", "s;\n        animation-timing-function: linear; \n    }\n \n"], ["\n    position: absolute;\n    box-sizing: border-box;\n    width: 100%;\n    height: 100%;\n    border-radius: 50%;\n\n    &:nth-child(1) {\n        left: 0;\n        top: 0;\n        animation: ", " infinite;\n        border-bottom: 3px solid ", ";\n        animation-duration: ", "s;\n        animation-timing-function: linear;\n        \n    }\n    &:nth-child(2) {\n        right: 0;\n        top: 0;\n        animation: ", " infinite;\n        border-right: 3px solid ", ";\n        animation-duration: ", "s;\n        animation-timing-function: linear; \n    }\n    &:nth-child(3) {\n        right: 0;\n        bottom: 0;\n        animation: ", " infinite;\n        border-right: 3px solid ", ";\n        animation-duration: ", "s;\n        animation-timing-function: linear; \n    }\n \n"])), electronSpinnerAnimation1, function (props) { var _a; return (_a = props.style) === null || _a === void 0 ? void 0 : _a.color; }, function (props) { return props.itemProp; }, electronSpinnerAnimation2, function (props) { var _a; return (_a = props.style) === null || _a === void 0 ? void 0 : _a.color; }, function (props) { return props.itemProp; }, electronSpinnerAnimation3, function (props) { var _a; return (_a = props.style) === null || _a === void 0 ? void 0 : _a.color; }, function (props) { return props.itemProp; });
export { ElectronSpinner, ElectronLine };
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5;
